config/routes.rb
HomemadeShop::Application.routes.draw do
  require 'sidekiq/web'

  resources :carts

  devise_for :users, :controllers => {:registrations => "registrations", :confirmations => "confirmations"}
  get 'store/index'

  resources :items

  resources :items do
    resources :line_items
  end

  resources :categories, only: [:index]
  mount Sidekiq::Web, at: '/sidekiq'

  root 'store#index', as: 'store'

end

app/models/item.rb
class Item < ActiveRecord::Base
	has_many :line_items
	belongs_to :category
	belongs_to :user

	validates :category_id, presence: true
	validates :title, presence: true
	validates :price, presence: true, :numericality => { :greater_than => 0}
	validates :count, presence: true, :numericality => { :greater_than => 0, :less_than_or_equal_to => 99 }
	validates :general_description, presence: true
	validates :user_id, presence: true

	before_destroy :ensure_not_referenced_by_any_line_item


	def owner?(current_user)
	  current_user == self.user
	end

	private

	def ensure_not_referenced_by_any_line_item
		if line_items.empty?
			return true
		else
			errors.add(:base, 'Line Items present')
			return false
		end
	end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_item, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate_user!, only:[:new]
  rescue_from ActiveRecord::RecordNotFound, with: :invalid_item


  # GET /items
  # GET /items.json
  def index
    if(params[:category_id])
      @items = Item.where(category_id: params[:category_id])
    else
      @items = Item.all
    end
    respond_to do |format|
      format.json { render json: @items }
      format.html
      format.rss
    end
  end

  # GET /items/1
  # GET /items/1.json
  def show
    respond_to do |format|
      format.html
      format.json { render json: @item }
    end
  end

  # GET /items/new
  def new
    @item = Item.new
    @categories = Category.all.by_name
  end

  # GET /items/1/edit
  def edit
    unless @item.owner?(current_user)#current_user!= @item.user
      redirect_to store_url, notice: 'To nie jest Twój przedmiot.'
    else
      @categories = Category.all.by_name
    end
  end

  # POST /items
  # POST /items.json
  def create
    @item = Item.new(item_params)
    @categories = Category.all.by_name
    @item.user = current_user

    respond_to do |format|
      if @item.save
        format.html { redirect_to @item, notice: 'Przedmiot został pomyślnie dodany.' }
        format.json { render action: 'show', status: :created, location: @item }
      else
        format.html { render action: 'new' }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /items/1
  # PATCH/PUT /items/1.json
  def update
    respond_to do |format|
      if @item.update(item_params)
        format.html { redirect_to @item, notice: 'Item was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end
  # DELETE /items/1
  # DELETE /items/1.json
  def destroy
    @item.destroy
    respond_to do |format|
      format.html { redirect_to items_url }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_item
    @item = Item.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def item_params
    params.require(:item).permit(:title, :detailed_description, :general_description, :price, :image_url, :category_id, :count, :todo)
  end

  def invalid_item
    logger.error "Attempt to access invalid_item #{params[:id]}"
    redirect_to store_url, notice: 'Przedmiot nie istnieje, przepraszamy.'
  end
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/_form.html.erb
<br>
<%= simple_form_for @item do |f| %>

<div class="form-group">
  <%= f.input :title %>
</div>

<div class="form-group">
  <%= f.input :general_description %>
</div>

<div class="form-group">
  <%= f.input :detailed_description %>
</div>

<div class="form-group">
  <%= f.input :price, as: :decimal %>
</div>

<div class="form-group">
  <%= f.input :count, as: :integer %>
</div>

<div class="form-group">
  <%= f.association :category, collection: @categories, prompt: "Wybierz", label: "Kategoria" %>
</div>

<div class="form-group">
   <%= label :todo, 'Wykonam na zamówienie:', class: "todo_label" %>
    <%= f.collection_radio_buttons :todo, [[true, 'Tak'] ,[false, 'Nie']], :first, :last  %>
</div>

<div class="form-group">
  <%= f.submit  "Dodaj przedmiot", class: "btn btn-primary btn-sm"%>
</div>

<% end %>




<div ng-controller="ItemController">
<div>

app/views/items/edit.html.erb
<h1>Editing item</h1>

<%= render 'form' %>

<%= link_to 'Show', @item %> |
<%= link_to 'Back', items_path %>

app/views/items/index.html.erb
<h1>Przedmioty</h1>
<div ng-controller="ItemsController">
  <table>
    <tr ng-repeat="item in items">
      <td>
        <%= image_tag("obraz.jpg", class: 'list_image') %>
      </td>
      <td class="list_description">
        <dl>
          <dt>{{item.title}}</dt>
          <dd>{{item.general_description}}</dd>
        </dl>
      </td>
      <td class="list_actions">
        <%= link_to 'Pokaż przedmiot', "#{items_path()}/{{item.id}}" %><br/>
      </td>
    </tr>
  </table>
</div>
<br>
<%= link_to 'Nowy przedmiot', new_item_path %> |
<%= link_to 'Strona główna', store_path %>

app/views/items/new.html.erb
<h1>Nowy przedmiot</h1>

<%= render 'form' %>

<%= link_to 'Powrót', items_path %>

app/views/items/show.html.erb
<% if notice %>
  <p class="alert alert-success"><%= notice %></p>
<% end %>

<script>
  window.Id = <%= @item.id %>
</script>

<div ng-controller="LineItemsController">

<div ng-if= "linkUpdated">
    <div class="alert alert-success" >
      <button type="button" class="close" data-dismiss="alert"> &times;</button>
      Kupiłeś przedmiot {{item.title}}!
    </div>
</div>


<div ng-if= "errors">
    <div class="alert alert-danger" >
      <button type="button" class="close" data-dismiss="alert"> &times;</button>
      Niestety nie udało się kupić przedmiotu.
    </div>
</div>

<p>
  <strong>Tytuł przedmiotu:</strong>
  {{item.title}}  
</p>

<p>
  <strong>Szczegółowy opis:</strong>
  {{item.detailedDescription}}  
</p>

<p>
  <strong>Ogólny opis:</strong>
  {{item.generalDescription}}  
</p>

<p>
  <strong>Cena:</strong>
  {{item.price}}  
</p>

<p>
  <strong>Tytuł kategorii:</strong>
  {{item.categoryTitle}}  
</p>

<p>
  <strong>Właściciel:</strong>
  {{item.userEmail}}  
</p>

<p>
  <strong>Na zamówienie:</strong>
  {{item.todo}}  
</p>

<% if !@item.owner?(current_user) && user_signed_in? %>
  <button ng-click='addItem()'>
    Kup
  </button>
<% end %>

</div>

<% unless user_signed_in? %>
  <%= button_to "Zaloguj się aby kupić", new_user_session_path %>
<% end %>

<% if @item.owner?(current_user) %>
  <%= link_to 'Edytuj', edit_item_path(@item) %> |
<% end %>

<%= link_to 'Wróć', store_url %>