config/routes.rb
HomemadeShop::Application.routes.draw do
  require 'sidekiq/web'

  resources :carts

  devise_for :users, :controllers => {:registrations => "registrations", :confirmations => "confirmations"}
  get 'store/index'

  resources :items

  resources :items do
    resources :line_items
  end

  resources :categories, only: [:index]
  mount Sidekiq::Web, at: '/sidekiq'

  root 'store#index', as: 'store'

end

app/controllers/store_controller.rb
class StoreController < ApplicationController
	include CurrentCart
  before_action :set_cart
	def index
		@items = Item.all
		respond_to do |format|
			format.html
			format.json { render json: @items }
		end
	end
end

app/helpers/store_helper.rb
module StoreHelper
end

app/views/store/index.html.erb
<div ng-controller="ItemsController">
	<div id="banner">
		<%= image_tag("logo.jpg") %>
		<a ng-click ='fetchItems()'>Homemade Shop</a>
		<p class="my_nav_up">

			<% if user_signed_in? %>
				Jesteś zalogowany jako: <strong><%= current_user.email %></strong>.
				<span>
				<%= link_to 'Edytuj profil', edit_user_registration_path,
																		:class => 'navbar-link' %> |
				<%= link_to "Wyloguj się", destroy_user_session_path,
															method: :delete, :class => 'navbar-link'  %>
				</span>
			<% else %>
				<%= link_to "Rejestracja", new_user_registration_path, :class => 'navbar-link'  %> |
				<%= link_to "Logowanie", new_user_session_path, :class => 'navbar-link'  %>
			<% end %>

			<% if notice %>
				<p class="alert alert-success"><%= notice %></p>
			<% end %>

			<% if alert %>
				<p class="alert alert-danger"><%= alert %></p>
			<% end %>

		</p>
	</div>
<!-- <div ng-controller="LoginCtrl">
<div class="body">
  <div>Email: <input ng-model="login_user.email" /></div>
  <div>Password: <input type="password" ng-model="login_user.password" /></div>

  <button ng-click="login()" class="btn btn-primary" >Login</button>
</div>
</div>
 -->
	<div id="columns">
		<div id="left">
			<p ng-init=fetchCategories()>Kategorie:</p>
			<div class="category_listing" ng-repeat="category in categories">
				<ul class="nav nav-pills">
					<li ng-class="{ active: categoryIsSelected(category.id)}">
						<a ng-click ='fetchItemsForCategory(category)'>{{category.title}}</a>
					</li>
				</ul>
			</div>		
		</div>
		<div id="right">
		  <% if @cart %>
			<h5>Twoje kupione przedmioty</h5>
			<table>
				<% @cart.line_items.each do |item| %>
					<tr>
						<td><%= item.quantity %>&times;</td>
						<td><%= link_to item.item.title, item_path(item) %></td>
						<td class="item_price"><%= number_to_currency(item.total_price, :unit => "PLN ") %></td>
					</tr>
				<% end %>
				<tr class="total_line">
					<td></td>
					<td></td>
					<td class="total_cell"><%= number_to_currency(@cart.total_price, :unit => "PLN ") %></td>
				</tr>
				</table>
		  <% end %>
		</div>
		<div id="main">
			<h1>Oferty: <a class="newitem"><%= link_to 'Nowa oferta', new_item_path %></a></h1>
			<div class="entry" ng-repeat="item in items">
				<%= image_tag("obraz.jpg") %>
				<div class="list_actions">
					<%= link_to 'Pokaż przedmiot', "#{items_path()}/{{item.id}}" %>
				</div>
				<h3 ng-style="{ 'color': setColor({{item.count}},{{item.offers}}), 'text-decoration': setDecoration({{item.count}}, {{item.offers}}, '{{item.todo}}' ) }">{{item.title}}</h3>
				x{{item.count}}
				<p>{{item.generalDescription}}</p>
				<div class="show_owner">
					{{item.userEmail}}
				</div>
				<div class="price_line">
					<div class="price">{{item.price | currency:'PLN '}}</div>
					<div class="offers_show">Kupujących:
						<div class="offers">
						{{item.offers}}
						</div>
					</div> 
				</div>
			</div>
		</div>
	</div>
</div>